"""fix DefectStatusEnum

Revision ID: 72cfa17c102b
Revises: 860c57a6b985
Create Date: 2025-09-24 16:36:44.345374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cfa17c102b'
down_revision: Union[str, None] = '860c57a6b985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
