"""add_status_to_projects

Revision ID: 860c57a6b985
Revises: d65046a5311b
Create Date: 2025-09-24 14:35:31.262662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860c57a6b985'
down_revision: Union[str, None] = 'd65046a5311b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'COMPLETED', 'PAUSED', name='project_status', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###
