"""Create report

Revision ID: d65046a5311b
Revises: 16a7c401b6fb
Create Date: 2025-09-17 17:11:10.210433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65046a5311b'
down_revision: Union[str, None] = '16a7c401b6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_reports_title'), 'reports', ['title'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.alter_column('audit_logs', 'table_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('audit_logs', 'comment',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.alter_column('defects', 'priority',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='defect_priority', native_enum=False),
               existing_nullable=False)
    op.alter_column('defects', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('NEW', 'IN_PROGRESS', 'UNDER_REVIEW', 'CLOSED', 'CANCELED', name='defect_status', native_enum=False),
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('ENGINEER', 'MANAGER', 'LEADER', 'SUPERADMIN', name='role_name', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'name',
               existing_type=sa.Enum('ENGINEER', 'MANAGER', 'LEADER', 'SUPERADMIN', name='role_name', native_enum=False),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.alter_column('defects', 'status',
               existing_type=sa.Enum('NEW', 'IN_PROGRESS', 'UNDER_REVIEW', 'CLOSED', 'CANCELED', name='defect_status', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.alter_column('defects', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='defect_priority', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.alter_column('audit_logs', 'comment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('audit_logs', 'table_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_title'), table_name='reports')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
