name: Defect Management System CI

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r req.txt
        pip install fastapi uvicorn

    - name: Start FastAPI application
      working-directory: ./backend
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep
        echo "FastAPI server started"

    - name: Check server availability
      run: |
        curl --fail --retry 3 --retry-delay 5 http://localhost:8000/docs || exit 1
        echo "Server is up and running"

    - name: Stop FastAPI application
      run: |
        pkill -f uvicorn
        echo "FastAPI server stopped"